name: Deploy pages
on: push
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - run: npx playwright install
      - name: Build
        run: bun run build --base /kotlin-goodies-seajug/
      - name: Build PDF
        run: bun run export --output dist/index.pdf
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
